version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: grading_user
      POSTGRES_PASSWORD: grading_password
      POSTGRES_DB: grading_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
  